C6.1_4.1
Nikolay38744/S_ol pull request #20
Opened 2023-07-20 14:46 UTC by Constantine7266

Все верно?

2023-07-20 14:56 UTC, Nikolay38744 commented on Нач/6.1/6.1_4.py
> +    ** - возведение в степень """
Приведи примеры для каждого оператора

2023-07-20 15:14 UTC, Nikolay38744 requested changes, later dismissed
Приведите примеры с каждым оператором

2023-07-21 08:24 UTC, Nikolay38744 commented on Нач/6.1/6.1_4.py
> +    ** - возведение в степень """
```suggestion
""" % - остаток от деление или деление по модулю 
    // - целочисленное деление или неполное частное 
    ** - возведение в степень """
```

2023-07-21 08:25 UTC, Nikolay38744 commented on Нач/6.1/6.1_4.py
> +    ** - возведение в степень """
Приведите пример с каждым оператором

2023-07-21 08:26 UTC, Nikolay38744 commented on Нач/6.1/6.1_4.py
> +    ** - возведение в степень """
Приведите пример с каждым оператором

2023-07-21 08:27 UTC, Constantine7266 commented on Нач/6.1/6.1_4.py
> +    ** - возведение в степень """
Хорошо

2023-07-21 09:02 UTC, Nikolay38744 commented on Нач/6.1/6.1_4.py
> +# TODO: результат 25
Все верно

2023-07-21 09:03 UTC, merged

2023-07-21 09:04 UTC, Nikolay38744 commented
Не забудь удалить ветку feature